version: '3.9'
services:
  project_service:
    depends_on:
      - db
    build: 
      context: ./src/services/project_service
      args:
        ENVIRONMENT: prod
    environment:
      - "PORT=8080"
      - "HOST=0.0.0.0"
      - "DB_USER=root"
      - "DB_PASSWORD=root"
      - "DB_NAME=task_wizard"
      - "DB_HOST=db"
      - "DB_PORT=3306"
      - "DB_MAX_IDLE_CONNECTIONS=10"
      - "DB_MAX_OPEN_CONNECTIONS=10"
      - "DB_MAX_CONNECTION_LIFETIME=3"  # minutes
      - "LOG_LEVEL=INFO"
    ports:
      - 8080:8080
    tty: true
    # volumes:
    #   - ./src/services/project_service/src:/service
  db:
    build:
      context: ./src/services/db
    environment:
      - "MARIADB_ROOT_PASSWORD=root"
